{% set name = "pyone" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyone-{{ version }}.tar.gz
  sha256: b543f05149a0fd2a9c56f72842acd210ad7614138b991fb2639d24e7f069753e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - lxml
    - dict2xml
    - xmltodict
    - six
    - tblib
    - requests

test:
  imports:
    - pyone
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://opennebula.io
  summary: Python Bindings for OpenNebula XML-RPC API
  description: |
    PyONE is an implementation of OpenNebula XML-RPC bindings in Python. It
    has been designed as a wrapper for the XML-RPC methods, with some basic
    helpers. This means that you should be familiar with the XML-RPC API and
    the XML formats returned by the OpenNebula core.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/OpenNebula/one/tree/master/src/oca/python
  doc_url: https://docs.opennebula.io/6.10/integration_and_development/system_interfaces/python.html

extra:
  recipe-maintainers:
    - manics
